/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as CheckoutDepositRouteImport } from './routes/checkout/deposit'
import { Route as CheckoutEmergencyRepairRouteImport } from './routes/checkout/emergency-repair'
import { Route as CheckoutExpressRouteImport } from './routes/checkout/express'
import { Route as CheckoutInspectionRouteImport } from './routes/checkout/inspection'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as DashboardCompanyIdRouteImport } from './routes/dashboard/$companyId'
import { Route as ApiAdminFinalInvoiceRouteImport } from './routes/api/admin/final-invoice'
import { Route as ApiAdminLeadsRouteImport } from './routes/api/admin/leads'
import { Route as ApiAdminMembershipsRouteImport } from './routes/api/admin/memberships'
import { Route as ApiDashboardLeadsRouteImport } from './routes/api/dashboard/leads'
import { Route as ApiPaymentsConfirmRouteImport } from './routes/api/payments/confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDepositRoute = CheckoutDepositRouteImport.update({
  id: '/checkout/deposit',
  path: '/checkout/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutEmergencyRepairRoute = CheckoutEmergencyRepairRouteImport.update({
  id: '/checkout/emergency-repair',
  path: '/checkout/emergency-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutExpressRoute = CheckoutExpressRouteImport.update({
  id: '/checkout/express',
  path: '/checkout/express',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutInspectionRoute = CheckoutInspectionRouteImport.update({
  id: '/checkout/inspection',
  path: '/checkout/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompanyIdRoute = DashboardCompanyIdRouteImport.update({
  id: '/dashboard/$companyId',
  path: '/dashboard/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFinalInvoiceRoute = ApiAdminFinalInvoiceRouteImport.update({
  id: '/api/admin/final-invoice',
  path: '/api/admin/final-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLeadsRoute = ApiAdminLeadsRouteImport.update({
  id: '/api/admin/leads',
  path: '/api/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMembershipsRoute = ApiAdminMembershipsRouteImport.update({
  id: '/api/admin/memberships',
  path: '/api/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardLeadsRoute = ApiDashboardLeadsRouteImport.update({
  id: '/api/dashboard/leads',
  path: '/api/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsConfirmRoute = ApiPaymentsConfirmRouteImport.update({
  id: '/api/payments/confirm',
  path: '/api/payments/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/emergency-repair': typeof CheckoutEmergencyRepairRoute
  '/checkout/express': typeof CheckoutExpressRoute
  '/checkout/inspection': typeof CheckoutInspectionRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/api/admin/final-invoice': typeof ApiAdminFinalInvoiceRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/memberships': typeof ApiAdminMembershipsRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRoute
  '/api/payments/confirm': typeof ApiPaymentsConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/emergency-repair': typeof CheckoutEmergencyRepairRoute
  '/checkout/express': typeof CheckoutExpressRoute
  '/checkout/inspection': typeof CheckoutInspectionRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/api/admin/final-invoice': typeof ApiAdminFinalInvoiceRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/memberships': typeof ApiAdminMembershipsRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRoute
  '/api/payments/confirm': typeof ApiPaymentsConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/emergency-repair': typeof CheckoutEmergencyRepairRoute
  '/checkout/express': typeof CheckoutExpressRoute
  '/checkout/inspection': typeof CheckoutInspectionRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/api/admin/final-invoice': typeof ApiAdminFinalInvoiceRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/admin/memberships': typeof ApiAdminMembershipsRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRoute
  '/api/payments/confirm': typeof ApiPaymentsConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/leads'
    | '/api/leads'
    | '/checkout/deposit'
    | '/checkout/emergency-repair'
    | '/checkout/express'
    | '/checkout/inspection'
    | '/checkout/success'
    | '/dashboard/$companyId'
    | '/api/admin/final-invoice'
    | '/api/admin/leads'
    | '/api/admin/memberships'
    | '/api/dashboard/leads'
    | '/api/payments/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/leads'
    | '/api/leads'
    | '/checkout/deposit'
    | '/checkout/emergency-repair'
    | '/checkout/express'
    | '/checkout/inspection'
    | '/checkout/success'
    | '/dashboard/$companyId'
    | '/api/admin/final-invoice'
    | '/api/admin/leads'
    | '/api/admin/memberships'
    | '/api/dashboard/leads'
    | '/api/payments/confirm'
  id:
    | '__root__'
    | '/'
    | '/admin/leads'
    | '/api/leads'
    | '/checkout/deposit'
    | '/checkout/emergency-repair'
    | '/checkout/express'
    | '/checkout/inspection'
    | '/checkout/success'
    | '/dashboard/$companyId'
    | '/api/admin/final-invoice'
    | '/api/admin/leads'
    | '/api/admin/memberships'
    | '/api/dashboard/leads'
    | '/api/payments/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  CheckoutDepositRoute: typeof CheckoutDepositRoute
  CheckoutEmergencyRepairRoute: typeof CheckoutEmergencyRepairRoute
  CheckoutExpressRoute: typeof CheckoutExpressRoute
  CheckoutInspectionRoute: typeof CheckoutInspectionRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DashboardCompanyIdRoute: typeof DashboardCompanyIdRoute
  ApiAdminFinalInvoiceRoute: typeof ApiAdminFinalInvoiceRoute
  ApiAdminLeadsRoute: typeof ApiAdminLeadsRoute
  ApiAdminMembershipsRoute: typeof ApiAdminMembershipsRoute
  ApiDashboardLeadsRoute: typeof ApiDashboardLeadsRoute
  ApiPaymentsConfirmRoute: typeof ApiPaymentsConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/deposit': {
      id: '/checkout/deposit'
      path: '/checkout/deposit'
      fullPath: '/checkout/deposit'
      preLoaderRoute: typeof CheckoutDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/emergency-repair': {
      id: '/checkout/emergency-repair'
      path: '/checkout/emergency-repair'
      fullPath: '/checkout/emergency-repair'
      preLoaderRoute: typeof CheckoutEmergencyRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/express': {
      id: '/checkout/express'
      path: '/checkout/express'
      fullPath: '/checkout/express'
      preLoaderRoute: typeof CheckoutExpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/inspection': {
      id: '/checkout/inspection'
      path: '/checkout/inspection'
      fullPath: '/checkout/inspection'
      preLoaderRoute: typeof CheckoutInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$companyId': {
      id: '/dashboard/$companyId'
      path: '/dashboard/$companyId'
      fullPath: '/dashboard/$companyId'
      preLoaderRoute: typeof DashboardCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/final-invoice': {
      id: '/api/admin/final-invoice'
      path: '/api/admin/final-invoice'
      fullPath: '/api/admin/final-invoice'
      preLoaderRoute: typeof ApiAdminFinalInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/leads': {
      id: '/api/admin/leads'
      path: '/api/admin/leads'
      fullPath: '/api/admin/leads'
      preLoaderRoute: typeof ApiAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/memberships': {
      id: '/api/admin/memberships'
      path: '/api/admin/memberships'
      fullPath: '/api/admin/memberships'
      preLoaderRoute: typeof ApiAdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/leads': {
      id: '/api/dashboard/leads'
      path: '/api/dashboard/leads'
      fullPath: '/api/dashboard/leads'
      preLoaderRoute: typeof ApiDashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/confirm': {
      id: '/api/payments/confirm'
      path: '/api/payments/confirm'
      fullPath: '/api/payments/confirm'
      preLoaderRoute: typeof ApiPaymentsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  CheckoutDepositRoute: CheckoutDepositRoute,
  CheckoutEmergencyRepairRoute: CheckoutEmergencyRepairRoute,
  CheckoutExpressRoute: CheckoutExpressRoute,
  CheckoutInspectionRoute: CheckoutInspectionRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DashboardCompanyIdRoute: DashboardCompanyIdRoute,
  ApiAdminFinalInvoiceRoute: ApiAdminFinalInvoiceRoute,
  ApiAdminLeadsRoute: ApiAdminLeadsRoute,
  ApiAdminMembershipsRoute: ApiAdminMembershipsRoute,
  ApiDashboardLeadsRoute: ApiDashboardLeadsRoute,
  ApiPaymentsConfirmRoute: ApiPaymentsConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
